export const projects = [
  {
    title: 'MedsoServe- Hospital Management System',
    description: "Using React, Node.js, Express & MongoDB you'll learn how to build a Full Stack MERN Application - from start to finish. The App is called Memories and it is a simple social media app that allows users to post interesting events that happened in their lives.",
      image: '/images/1.png',
      tags: ['HTML', 'CSS', 'JavaScript', 'PHP'],
    source:'https://google.com',
    visit: 'https://github.com/Ahib-Afnan-Siam/MedsoServe---Hospital-Management-System.git',
    id: 0,
  },
  {
    title: 'Language Translator',
    description:"Python-based language translator app that converts text between multiple languages using a user-friendly interface.",
    image: '/images/2.png',
    tags: ['Python', 'TkInter'],
    source: 'https://google.com',
    visit: 'https://github.com/Ahib-Afnan-Siam/Language-Translator.git',
    id: 1,
  },
  {
    title: 'Car Price Predition',
    description: "A Python-based car price prediction project using machine learning to estimate vehicle prices based on various features. ",
      image: '/images/3.jpg',
      tags: ['Python', 'NumPy', 'Pandas', 'MatPoltLib'],
    source: 'https://google.com',
    visit: 'https://github.com/Ahib-Afnan-Siam/Car-Price-Predition.git',
    id: 2,
  },
  {
    title: 'Space Invaders',
    description: "A Python-based Space Invaders game created using Pygame. Control your spaceship, shoot down aliens, and avoid enemy fire. Features increasing difficulty, a scoring system, and multiple lives.",
    image: '/images/4.jpg',
    tags: ['Python', 'TkInter'],
    source: 'https://google.com',
    visit: 'https://github.com/Ahib-Afnan-Siam/Space-Invaders.git',
    id: 3,
  },
  {
    title: 'Food Ordering App',
    description: "A Tkinter-based food ordering app featuring interactive menus with images, cart management, delivery or pickup options, and order history tracking. ",
    image: '/images/4.jpg',
    tags: ['Python', 'TkInter'],
    source: 'https://google.com',
    visit: 'https://github.com/Ahib-Afnan-Siam/Food-Ordering-App.git',
    id: 4,
  },
  {
    title: 'My Calculator',
    description: "A Python-based calculator that supports basic arithmetic, trigonometric functions, square roots, and squares, designed with an intuitive interface.",
    image: '/images/4.jpg',
    tags: ['Python', 'TkInter'],
    source: 'https://google.com',
    visit: 'https://github.com/Ahib-Afnan-Siam/My-Calculator.git',
    id: 5,
  },
];

export const TimeLineData = [
  { year: 2017, text: 'Started my journey', },
  { year: 2018, text: 'Worked as a freelance developer', },
  { year: 2019, text: 'Founded JavaScript Mastery', },
  { year: 2020, text: 'Shared my projects with the world', },
  { year: 2021, text: 'Started my own platform', },
];